name: Check News entry
on:
  pull_request:

jobs:
  Check-Changelog:
    name: Check that the News.md was updated
    runs-on: ubuntu-latest
    steps:
      - uses: tarides/changelog-check-action@v3
        with:
          changelog: NEWS.md